Импорт pandas и numpy, считывание датасета.

In [12]:
import pandas as pd
import numpy as np

df = pd.read_csv("weatherAUS_clear.csv")
df

,Unnamed: 0,Date,Location,MinTemp,MaxTemp,Rainfall,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,0,2008-12-01,Albury,13.4,22.9,0.6,W,44.0,W,WNW,20.0,24.0,71.0,22.0,1007.7,1007.1,16.9,21.8,No,No
1,1,2008-12-02,Albury,7.4,25.1,0.0,WNW,44.0,NNW,WSW,4.0,22.0,44.0,25.0,1010.6,1007.8,17.2,24.3,No,No
2,2,2008-12-03,Albury,12.9,25.7,0.0,WSW,46.0,W,WSW,19.0,26.0,38.0,30.0,1007.6,1008.7,21.0,23.2,No,No
3,3,2008-12-04,Albury,9.2,28.0,0.0,NE,24.0,SE,E,11.0,9.0,45.0,16.0,1017.6,1012.8,18.1,26.5,No,No
4,4,2008-12-05,Albury,17.5,32.3,1.0,W,41.0,ENE,NW,7.0,20.0,82.0,33.0,1010.8,1006.0,17.8,29.7,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140782,145454,2017-06-20,Uluru,3.5,21.8,0.0,E,31.0,ESE,E,15.0,13.0,59.0,27.0,1024.7,1021.2,9.4,20.9,No,No
140783,145455,2017-06-21,Uluru,2.8,23.4,0.0,E,31.0,SE,ENE,13.0,11.0,51.0,24.0,1024.6,1020.3,10.1,22.4,No,No
140784,145456,2017-06-22,Uluru,3.6,25.3,0.0,NNW,22.0,SE,N,13.0,9.0,56.0,21.0,1023.5,1019.1,10.9,24.5,No,No
140785,145457,2017-06-23,Uluru,5.4,26.9,0.0,N,37.0,SE,WNW,9.0,9.0,53.0,24.0,1021.0,1016.8,12.5,26.1,No,No
140786,145458,2017-06-24,Uluru,7.8,27.0,0.0,SE,28.0,SSE,N,13.0,7.0,51.0,24.0,1019.4,1016.5,15.1,26.0,No,No

Использование OrdinalEncoder, преобразует каждое строковое значение в целое число, и запоминает его в массив(датафрейм не трогает)

Первое уникальное значение в вашем столбце становится 1, второе становится 2, третье становится 3 и так далее.

In [14]:
from sklearn.preprocessing import OrdinalEncoder

Oenc = OrdinalEncoder()
Oenc.fit(df[['Location','WindGustDir','WindDir9am','WindDir3pm']])
#df
Oenc.categories_

[array(['Adelaide', 'Albany', 'Albury', 'AliceSprings', 'BadgerysCreek',
        'Ballarat', 'Bendigo', 'Brisbane', 'Cairns', 'Canberra', 'Cobar',
        'CoffsHarbour', 'Dartmoor', 'Darwin', 'GoldCoast', 'Hobart',
        'Katherine', 'Launceston', 'Melbourne', 'MelbourneAirport',
        'Mildura', 'Moree', 'MountGambier', 'MountGinini', 'Newcastle',
        'Nhil', 'NorahHead', 'NorfolkIsland', 'Nuriootpa', 'PearceRAAF',
        'Penrith', 'Perth', 'PerthAirport', 'Portland', 'Richmond', 'Sale',
        'SalmonGums', 'Sydney', 'SydneyAirport', 'Townsville',
        'Tuggeranong', 'Uluru', 'WaggaWagga', 'Walpole', 'Watsonia',
        'Williamtown', 'Witchcliffe', 'Wollongong', 'Woomera'],
       dtype=object),
 array(['E', 'ENE', 'ESE', 'N', 'NE', 'NNE', 'NNW', 'NW', 'S', 'SE', 'SSE',
        'SSW', 'SW', 'Unknown', 'W', 'WNW', 'WSW'], dtype=object),
 array(['E', 'ENE', 'ESE', 'N', 'NE', 'NNE', 'NNW', 'NW', 'S', 'SE', 'SSE',
        'SSW', 'SW', 'Unknown', 'W', 'WNW', 'WSW'], dtype=object),
 array(['E', 'ENE', 'ESE', 'N', 'NE', 'NNE', 'NNW', 'NW', 'S', 'SE', 'SSE',
        'SSW', 'SW', 'Unknown', 'W', 'WNW', 'WSW'], dtype=object)]

Использование OrdinalEncoder с fit_transform (заменяет значения в датафрейме на индексы массива)

In [15]:
from sklearn.preprocessing import OrdinalEncoder

Oenc = OrdinalEncoder()
df[['Location','WindGustDir','WindDir9am','WindDir3pm']] = Oenc.fit_transform(df[['Location','WindGustDir','WindDir9am','WindDir3pm']])
df
#Oenc.categories_

,Unnamed: 0,Date,Location,MinTemp,MaxTemp,Rainfall,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,0,2008-12-01,2.0,13.4,22.9,0.6,14.0,44.0,14.0,15.0,20.0,24.0,71.0,22.0,1007.7,1007.1,16.9,21.8,No,No
1,1,2008-12-02,2.0,7.4,25.1,0.0,15.0,44.0,6.0,16.0,4.0,22.0,44.0,25.0,1010.6,1007.8,17.2,24.3,No,No
2,2,2008-12-03,2.0,12.9,25.7,0.0,16.0,46.0,14.0,16.0,19.0,26.0,38.0,30.0,1007.6,1008.7,21.0,23.2,No,No
3,3,2008-12-04,2.0,9.2,28.0,0.0,4.0,24.0,9.0,0.0,11.0,9.0,45.0,16.0,1017.6,1012.8,18.1,26.5,No,No
4,4,2008-12-05,2.0,17.5,32.3,1.0,14.0,41.0,1.0,7.0,7.0,20.0,82.0,33.0,1010.8,1006.0,17.8,29.7,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140782,145454,2017-06-20,41.0,3.5,21.8,0.0,0.0,31.0,2.0,0.0,15.0,13.0,59.0,27.0,1024.7,1021.2,9.4,20.9,No,No
140783,145455,2017-06-21,41.0,2.8,23.4,0.0,0.0,31.0,9.0,1.0,13.0,11.0,51.0,24.0,1024.6,1020.3,10.1,22.4,No,No
140784,145456,2017-06-22,41.0,3.6,25.3,0.0,6.0,22.0,9.0,3.0,13.0,9.0,56.0,21.0,1023.5,1019.1,10.9,24.5,No,No
140785,145457,2017-06-23,41.0,5.4,26.9,0.0,3.0,37.0,9.0,15.0,9.0,9.0,53.0,24.0,1021.0,1016.8,12.5,26.1,No,No
140786,145458,2017-06-24,41.0,7.8,27.0,0.0,9.0,28.0,10.0,3.0,13.0,7.0,51.0,24.0,1019.4,1016.5,15.1,26.0,No,No

Использование LabelEncoder. LabelEncoder не возвращает датафрейм. Он также выводит значения, начинающиеся с 0, по сравнению с выводом значений OrdinalEncoder по умолчанию, начинающимся с 1.

In [16]:
from sklearn.preprocessing import LabelEncoder

Lenc = LabelEncoder()
Lenc.fit(df['RainTomorrow'])
df['RainTomorrow'] = Lenc.fit_transform(df['RainTomorrow'])
df

,Unnamed: 0,Date,Location,MinTemp,MaxTemp,Rainfall,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,0,2008-12-01,2.0,13.4,22.9,0.6,14.0,44.0,14.0,15.0,20.0,24.0,71.0,22.0,1007.7,1007.1,16.9,21.8,No,0
1,1,2008-12-02,2.0,7.4,25.1,0.0,15.0,44.0,6.0,16.0,4.0,22.0,44.0,25.0,1010.6,1007.8,17.2,24.3,No,0
2,2,2008-12-03,2.0,12.9,25.7,0.0,16.0,46.0,14.0,16.0,19.0,26.0,38.0,30.0,1007.6,1008.7,21.0,23.2,No,0
3,3,2008-12-04,2.0,9.2,28.0,0.0,4.0,24.0,9.0,0.0,11.0,9.0,45.0,16.0,1017.6,1012.8,18.1,26.5,No,0
4,4,2008-12-05,2.0,17.5,32.3,1.0,14.0,41.0,1.0,7.0,7.0,20.0,82.0,33.0,1010.8,1006.0,17.8,29.7,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140782,145454,2017-06-20,41.0,3.5,21.8,0.0,0.0,31.0,2.0,0.0,15.0,13.0,59.0,27.0,1024.7,1021.2,9.4,20.9,No,0
140783,145455,2017-06-21,41.0,2.8,23.4,0.0,0.0,31.0,9.0,1.0,13.0,11.0,51.0,24.0,1024.6,1020.3,10.1,22.4,No,0
140784,145456,2017-06-22,41.0,3.6,25.3,0.0,6.0,22.0,9.0,3.0,13.0,9.0,56.0,21.0,1023.5,1019.1,10.9,24.5,No,0
140785,145457,2017-06-23,41.0,5.4,26.9,0.0,3.0,37.0,9.0,15.0,9.0,9.0,53.0,24.0,1021.0,1016.8,12.5,26.1,No,0
140786,145458,2017-06-24,41.0,7.8,27.0,0.0,9.0,28.0,10.0,3.0,13.0,7.0,51.0,24.0,1019.4,1016.5,15.1,26.0,No,0

In [17]:
Lenc.classes_

array(['No', 'Yes'], dtype=object)

Использование OneHotEncoder, этот кодировщик берёт столбец с категориальными данными, который был предварительно закодирован в признак, и создаёт для него несколько новых столбцов. Числа заменяются на единицы и нули, в зависимости от того, какому столбцу какое значение присуще.

In [18]:
from sklearn.preprocessing import OneHotEncoder

Onhot = OneHotEncoder()
Onhot.fit(df[['RainToday']])
df

,Unnamed: 0,Date,Location,MinTemp,MaxTemp,Rainfall,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,0,2008-12-01,2.0,13.4,22.9,0.6,14.0,44.0,14.0,15.0,20.0,24.0,71.0,22.0,1007.7,1007.1,16.9,21.8,No,0
1,1,2008-12-02,2.0,7.4,25.1,0.0,15.0,44.0,6.0,16.0,4.0,22.0,44.0,25.0,1010.6,1007.8,17.2,24.3,No,0
2,2,2008-12-03,2.0,12.9,25.7,0.0,16.0,46.0,14.0,16.0,19.0,26.0,38.0,30.0,1007.6,1008.7,21.0,23.2,No,0
3,3,2008-12-04,2.0,9.2,28.0,0.0,4.0,24.0,9.0,0.0,11.0,9.0,45.0,16.0,1017.6,1012.8,18.1,26.5,No,0
4,4,2008-12-05,2.0,17.5,32.3,1.0,14.0,41.0,1.0,7.0,7.0,20.0,82.0,33.0,1010.8,1006.0,17.8,29.7,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140782,145454,2017-06-20,41.0,3.5,21.8,0.0,0.0,31.0,2.0,0.0,15.0,13.0,59.0,27.0,1024.7,1021.2,9.4,20.9,No,0
140783,145455,2017-06-21,41.0,2.8,23.4,0.0,0.0,31.0,9.0,1.0,13.0,11.0,51.0,24.0,1024.6,1020.3,10.1,22.4,No,0
140784,145456,2017-06-22,41.0,3.6,25.3,0.0,6.0,22.0,9.0,3.0,13.0,9.0,56.0,21.0,1023.5,1019.1,10.9,24.5,No,0
140785,145457,2017-06-23,41.0,5.4,26.9,0.0,3.0,37.0,9.0,15.0,9.0,9.0,53.0,24.0,1021.0,1016.8,12.5,26.1,No,0
140786,145458,2017-06-24,41.0,7.8,27.0,0.0,9.0,28.0,10.0,3.0,13.0,7.0,51.0,24.0,1019.4,1016.5,15.1,26.0,No,0

In [19]:
Onhot.categories_

[array(['No', 'Yes'], dtype=object)]

Перевод столбца у OneHotEncoder в массив

In [20]:
Onhot.transform(df[['RainToday']]).toarray()

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

Использование Normalizer, в отличие от предыдущих инструментов, по умолчанию приводит наблюдения (то есть строки, а не столбцы датафрейма) к единичной норме (или длине вектора, равной единице, unit norm, unit vector) или нормализует (normalizes) их.

In [21]:
from sklearn.preprocessing import Normalizer

Norm = Normalizer()
df[['Pressure9am','Pressure3pm']] = Norm.fit_transform(df[['Pressure9am','Pressure3pm']])
df

,Unnamed: 0,Date,Location,MinTemp,MaxTemp,Rainfall,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,0,2008-12-01,2.0,13.4,22.9,0.6,14.0,44.0,14.0,15.0,20.0,24.0,71.0,22.0,0.707317,0.706896,16.9,21.8,No,0
1,1,2008-12-02,2.0,7.4,25.1,0.0,15.0,44.0,6.0,16.0,4.0,22.0,44.0,25.0,0.708087,0.706125,17.2,24.3,No,0
2,2,2008-12-03,2.0,12.9,25.7,0.0,16.0,46.0,14.0,16.0,19.0,26.0,38.0,30.0,0.706721,0.707492,21.0,23.2,No,0
3,3,2008-12-04,2.0,9.2,28.0,0.0,4.0,24.0,9.0,0.0,11.0,9.0,45.0,16.0,0.708776,0.705433,18.1,26.5,No,0
4,4,2008-12-05,2.0,17.5,32.3,1.0,14.0,41.0,1.0,7.0,7.0,20.0,82.0,33.0,0.708788,0.705422,17.8,29.7,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140782,145454,2017-06-20,41.0,3.5,21.8,0.0,0.0,31.0,2.0,0.0,15.0,13.0,59.0,27.0,0.708315,0.705896,9.4,20.9,No,0
140783,145455,2017-06-21,41.0,2.8,23.4,0.0,0.0,31.0,9.0,1.0,13.0,11.0,51.0,24.0,0.708592,0.705618,10.1,22.4,No,0
140784,145456,2017-06-22,41.0,3.6,25.3,0.0,6.0,22.0,9.0,3.0,13.0,9.0,56.0,21.0,0.708628,0.705582,10.9,24.5,No,0
140785,145457,2017-06-23,41.0,5.4,26.9,0.0,3.0,37.0,9.0,15.0,9.0,9.0,53.0,24.0,0.708563,0.705648,12.5,26.1,No,0
140786,145458,2017-06-24,41.0,7.8,27.0,0.0,9.0,28.0,10.0,3.0,13.0,7.0,51.0,24.0,0.708113,0.706099,15.1,26.0,No,0

Использование train_test_split библиотеки Scikit-learn, который очень полезен для разделения датасетов, независимо от того, будете ли вы применять Scikit-learn для выполнения других задач машинного обучения, или нет.

In [22]:
from sklearn.model_selection import train_test_split

Y = df['RainTomorrow']
X = df.drop(columns=['RainTomorrow'])

x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size=0.2, random_state=42)